/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-echarts/src/bar-echart.vue')['default']
    BaseEchart: typeof import('./src/components/page-echarts/src/base-echart.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderCrumb: typeof import('./src/components/main-header/c-cpns/header-crumb.vue')['default']
    HeaderInfo: typeof import('./src/components/main-header/c-cpns/header-info/header-info.vue')['default']
    LineEchart: typeof import('./src/components/page-echarts/src/line-echart.vue')['default']
    MainHeader: typeof import('./src/components/main-header/main-header.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/map-echart.vue')['default']
    MianMenu: typeof import('./src/components/mian-menu/mian-menu.vue')['default']
    PageContent: typeof import('./src/components/page-content/page-content.vue')['default']
    PageModal: typeof import('./src/components/page-modal/page-modal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/page-search.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/pie-echart.vue')['default']
    RoseEchart: typeof import('./src/components/page-echarts/src/rose-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
